networks:
  default:

services:
  mysql:
    image:  mysql:8.0.28
    container_name: mysqldb
    hostname: mysqldb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./script:/docker-entrypoint-initdb.d 

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - default
  shiika:
    build: .
    ports:
      - "8080:8080"
    working_dir: /src
    command: "go run main.go login.go kaminoku.go simonoku.go user.go model.go"
    tty: true
    depends_on:
      - mysql
    networks:
      - default

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app:app
    environment:
      DOMAINS: 'api.shiika.trasta.dev -> http://shiika:8080'
      STAGE: 'local'
      FORCE_RENEW: 'false'
      CLIENT_MAX_BODY_SIZE: 0
    restart: unless-stopped
    volumes:
      - https-portal_data:/var/lib/https-portal

volumes:
  https-portal_data:
  mysql:
